20200816_レビュー依頼
KiHirofumi/work pull request #14
Opened 2020-08-16 06:19 UTC by nodami5

■作業内容
・質問羅列形式を作成しました
　→ユーザーの入力内容を想定して（手入力orメニュー）、入力内容に紐付く回答を出力させている
・LINEリッチメニューも追加しました（LINEデザイン側）

■課題
・入力（問い合わせ内容）と回答がリストで紐づいているので、プログラムだけ見ると分かりづらい
・まだ機能設計書のように項目や内容を設定できていない（チャットボットのインプット情報
の清書保留）

2020-08-16 10:38 UTC, KiHirofumi commented on README.md
> +
ここの部分はPull Requestsの練習だったので、今回は不要です。

2020-08-16 10:47 UTC, KiHirofumi commented on README.md
> +test[20200712][nodami]
ここの部分はPull Requestsの練習だったので、今回は不要です。

2020-08-25 04:08 UTC, KiHirofumi reviewed
レビューのコメント記載しました。

2020-08-25 04:08 UTC, KiHirofumi commented on main.py
> +##20200712一旦オウム返しに戻すため、コメントアウト
不要の場合、特に必要なければコメントアウトではなく行削除で大丈夫です。過去との比較はGitHub上で可能なためです。

2020-08-25 04:08 UTC, KiHirofumi commented on main.py
> +    else:
Else時はオウム返しおよび「質問」（inquiry_text）を返してくれると嬉しいです。

2020-08-29 09:39 UTC, youmiyamo commented on main.py
> +        line_bot_api.reply_message(
line 60のinquiry_textがコメントアウトされてるので、
この分岐に入ってもメッセージへの応答が出来ていないです。（作成途中かな？）

2020-08-29 11:46 UTC, KiHirofumi requested changes
いったんこちらのソースはマージしません。

2020-08-30 00:47 UTC, closed without merging